resolver: lts-8.2

packages:
  - '.'
  - location:
      git: https://github.com/serokell/kademlia.git
      commit: 278171b8ab104c78aa95bcdd9b63c8ced4fb1ed2
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport
      commit: f2321a103f53f51d36c99383132e3ffa3ef1c401
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport-tcp
      commit: eb1ed2fe4d4419c860ce060cb1091f7c8959134f
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport-inmemory
      commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
    extra-dep: true

nix:
  enable: false
  packages: []

extra-deps:
  - serokell-util-0.1.3.5
  - time-units-1.0.0
  - log-warper-1.0.2
  - universum-0.3

flags: {}
extra-package-dbs: []
