resolver: lts-7.13

packages:
  - '.'
  - location:
      git: https://github.com/serokell/kademlia.git
      commit: 278171b8ab104c78aa95bcdd9b63c8ced4fb1ed2
    extra-dep: true
  - location:
      git: https://github.com/serokell/log-warper.git
      commit: 14d0d2f391e2ebb6a9679f1dd117c325aff53637
    extra-dep: true
  - location:
      git: https://github.com/serokell/universum
      commit: db3cd301545e5da000e53ca2cdf274e0386192bf
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport-tcp
      commit: e03e2abade9211d22ed00d0de563d3904c439521
    extra-dep: true

extra-deps:
  - network-transport-inmemory-0.5.2

nix:
  enable: false
  packages: []

extra-deps:
  - serokell-util-0.1.2.3
  - time-units-1.0.0
  - pqueue-1.3.2
  - time-warp-1.1.1.0
  - aeson-extra-0.4.0.0
  - data-msgpack-0.0.8
  - recursion-schemes-5.0.1

flags: {}
extra-package-dbs: []
